In [1]:
# Built-in function/methods to create an array
import numpy as np

arr1 = np.zeros((3, 4), dtype = int)
print(arr1)
print(arr1.dtype)




[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [2]:
# Creating an array of ones
arr1 = np.ones((3, 4), dtype = int)
print(arr1)
print(arr1.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [11]:
# Creating an array of twos
arr1 = np.ones((3, 4), dtype = int)
print(arr1*2)
print(arr1.dtype)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
int64


In [12]:
# creating an empty array
np.empty((4,5))



array([[-1.28822975e-231, -1.28822975e-231,  9.38724727e-323,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 2.37663529e-312, -1.28822975e-231, -1.49457452e-154,
         1.48219694e-323,  0.00000000e+000]])

In [4]:
np.empty((2,2))

array([[2.12199579e-314, 0.00000000e+000],
       [5.35567160e-321, 1.47266508e-311]])

In [9]:
# Identity matrix

# 1 0 0 0 
# 0 1 0 0 
# 0 0 1 0
# 0 0 0 1

arr = np.eye(3)
# arr[::-1]
# arr.dtype = float
arr



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# linspace and arange

# arange(start, stop, step) - similar to range
# Difference between arange and range - arnage can create a sequence of float values

# arr = np.arange(2, 10, 1)
# print(arr)


# arr = np.arange(2, 5, 0.5)
# print(arr)


arr = np.linspace(2, 10, 9)#.reshape(3, 3)
print(arr)




[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [32]:
# 8/89

In [40]:
# Changing the shape of an array
# reshape(), shape

# reshape creates a new object
# shape attribute makes the changes to existing object

arr = np.linspace(2, 24, 12)

arr1 = arr.reshape(2, 6)
print(arr1)
# print()
# print(arr)

# arr.shape = (4,3)

# print(arr)






[[ 2.  4.  6.  8. 10. 12.]
 [14. 16. 18. 20. 22. 24.]]


In [51]:
arr = np.linspace(2, 24, 12)

arr1=arr.reshape(3, -5)

# arr.reshape(10, -1)

# arr.shape = 10, -10

arr1

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.]])

In [53]:
# Transpose - converts rows to columns and columns to rows

arr1.T


array([[ 2., 10., 18.],
       [ 4., 12., 20.],
       [ 6., 14., 22.],
       [ 8., 16., 24.]])

In [54]:
# To convert an arry of higher tdimension to one dimension
arr.ravel()

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [57]:
# Ordering = 
#     1. C like ordering - 'C'
#     2. Forton Like ordering - 'F'

arr1 = np.arange(1, 9)
print(arr1)


[1 2 3 4 5 6 7 8]


In [60]:
arr1.reshape((2, 4), order ='C')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
arr1.reshape((2, 4), order ='F')

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

# Operations on an array
        - Arithmetic Operation
        - Comparions
        - Equality 







In [63]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10,20,30,40,50])

print(arr1+arr2)

print(arr1-arr2)

print(arr1*arr2)    # Scalar product





[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]


In [66]:
# Product
#     1. Scalar
#     2. Vector - np.dot(arr1, arr2)
        # 1. No of col in first array and no of row in 2nd array should be same
        # 2. shape of resultant aray is (no of rows of 1st Array X no of cols of 2nd array)


# print(arr1*4)
print(arr1*arr2)




[ 10  40  90 160 250]


In [72]:
arr1 = np.array([[1, 2, 3, 4, 5]])


arr2 = np.array([[6],
                 [7],
                 [8]])

print(arr1*arr2)



[[ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]]


In [73]:
[[1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5]]

[[6, 6, 6, 6, 6],
 [7, 7, 7, 7, 7],
 [8, 8, 8, 8, 8],
 [9, 9, 9, 9, 9],
 [10,10,10,10,10]]

[[6, 6, 6, 6, 6],
 [7, 7, 7, 7, 7],
 [8, 8, 8, 8, 8],
 [9, 9, 9, 9, 9],
 [10, 10, 10, 10, 10]]

In [ ]:
np.dot()

In [88]:
arr1 = np.arange(25, 55).reshape(5, 6)
print(arr1)

arr2 = np.arange(25, 61).reshape(6, 6)
print(arr2)

print(arr1*arr2)

[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]]
[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


ValueError: operands could not be broadcast together with shapes (5,6) (6,6) 

In [89]:
np.dot(arr1, arr2)

array([[ 6705,  6870,  7035,  7200,  7365,  7530],
       [ 8145,  8346,  8547,  8748,  8949,  9150],
       [ 9585,  9822, 10059, 10296, 10533, 10770],
       [11025, 11298, 11571, 11844, 12117, 12390],
       [12465, 12774, 13083, 13392, 13701, 14010]])

In [84]:
arr3 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8 ]])

arr4 = np.array([[9,8, 10],
                 [7,6, 11],
                 [5,4, 12],
                 [3,2, 13]])

print(np.dot(arr3, arr4))

[[ 50  40 120]
 [146 120 304]]


In [95]:
# Comparison operation
# Returns a boolean matrix

arr1 = np.arange(1, 13).reshape(3, 4)
np.random.shuffle(arr1)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
arr1>8

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [97]:
arr1[arr1>8]

array([ 9, 10, 11, 12])

In [127]:
arr1 = np.arange(1, 7, 1)
arr1.shape=(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
arr2 = np.random.randint(1, 13, (4, 3))
arr2

array([[ 5,  8,  9],
       [ 2, 10,  2],
       [11,  7, 12],
       [ 3,  3, 12]])

In [100]:
arr1 > arr2

array([[ True, False, False],
       [ True, False,  True],
       [False, False, False],
       [False,  True, False]])

In [90]:
# Compound assignment operation

# arr1 += arr2
# arr1


19+89+183+107+120

518

In [101]:
# Unary Operations

np.sum(arr1)



69

In [102]:
np.max(arr1)

10

In [128]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
# Sum of all the elements along rows and columns

# Along rows
np.sum(arr1, axis = 0)



array([5, 7, 9])

In [133]:
# Along columns
np.sum(arr1, axis = 1)

array([ 6, 15])

In [131]:
np.max(arr1, axis = 0)


array([4, 5, 6])

In [132]:
np.max(arr1, axis = 1)

array([3, 6])

In [98]:
# INdexing and slicing on numpy array

arr1 = np.array([1,2,3,4,5,6,7,8,9])
# print(arr1[0])
# print(arr1[-1])

print(arr1[2:6])
print(arr1)





[3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [3]:
arr1 = np.random.randint(1, 20, (4, 4))
arr1


# Indexing on. 2D array
# arr_name[row_ind, col_ind]
# arr_name[row_Slicing, col_slicing]

array([[ 9,  5,  7,  7],
       [ 1,  5,  6, 18],
       [18, 18, 11,  9],
       [17, 19, 15, 18]])

In [4]:
# Accessing one row
print(arr1[0])
print(arr1[-1])

[9 5 7 7]
[17 19 15 18]


In [5]:
print(arr1[0][0])

9


In [6]:
# Accessing a column

print(arr1[::, 0])

[ 9  1 18 17]


In [7]:
# Accessing a column
print(arr1[::, -1])

[ 7 18  9 18]


In [8]:
print(arr1[2, 2])

11


In [9]:
arr1

array([[ 9,  5,  7,  7],
       [ 1,  5,  6, 18],
       [18, 18, 11,  9],
       [17, 19, 15, 18]])

In [10]:
print(arr1[1::2])

[[ 1  5  6 18]
 [17 19 15 18]]


In [11]:
print(arr1[::,1::2])

[[ 5  7]
 [ 5 18]
 [18  9]
 [19 18]]


In [12]:
print(arr1[3::, 3::])

[[18]]


In [13]:
print(arr1[1:4:2, 1:4:2])

[[ 5 18]
 [19 18]]


In [14]:
arr1

array([[ 9,  5,  7,  7],
       [ 1,  5,  6, 18],
       [18, 18, 11,  9],
       [17, 19, 15, 18]])

In [18]:
row_ind = [[1,2],[3,2]]
col_ind = [[2,1],[2,3]]
row_ind
# col_ind

[[1, 2], [3, 2]]

In [16]:
arr1[row_ind, col_ind]

array([[ 6, 18],
       [15,  9]])

In [50]:
# 3D array
arr1 = np.random.randint(1, 20, (4, 4, 4))
arr1

array([[[ 7, 14, 18,  6],
        [14, 10, 19,  7],
        [11, 16, 12,  9],
        [16,  5, 13, 16]],

       [[10, 17, 12, 11],
        [11, 14,  4, 17],
        [ 2, 19, 13,  6],
        [ 2, 13, 13,  7]],

       [[ 2,  6, 15,  7],
        [ 8, 19,  4, 15],
        [ 8,  5,  4,  9],
        [19, 10, 18,  5]],

       [[16,  9,  1, 16],
        [ 6, 19,  6, 12],
        [12,  6,  8, 18],
        [13,  3, 16, 18]]])

In [29]:
arr1[1:3][1][1::2, 1::2]

array([[ 6, 17],
       [ 9,  9]])

In [30]:
arr1[::2][1][::3, ::3]

array([[18,  3],
       [10,  9]])

In [41]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])
fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

In [42]:
k = np.array([[0,1],[1,2]])
k

array([[0, 1],
       [1, 2]])

In [43]:
v = np.array([[2,1],[3,3]])
v

array([[2, 1],
       [3, 3]])

In [44]:
fruit[k, v] = 'Watermelon'

In [45]:
fruit

array([['Banana', 'Mango', 'Watermelon', 'Avacado'],
       ['Papaya', 'Watermelon', 'Plum', 'Watermelon'],
       ['Apricot', 'Apple', 'Blue berry', 'Watermelon']], dtype='<U11')

In [138]:
arr1 = np.random.randint(1, 100, (6, 6))
arr1

array([[17, 41,  4, 26, 81, 84],
       [78, 28, 98, 16, 98, 84],
       [94, 82, 73, 93, 62, 81],
       [58, 76, 57, 60,  2, 19],
       [13,  7, 39, 12, 98,  6],
       [96, 49, 51, 92,  8, 99]])

In [139]:
arr1[arr1>50]

array([81, 84, 78, 98, 98, 84, 94, 82, 73, 93, 62, 81, 58, 76, 57, 60, 98,
       96, 51, 92, 99])

In [51]:
# How many element which are greater than 50

np.sum(arr1>15)



17

In [52]:
np.any(arr1>15)

True

In [47]:
np.all(arr1>15)

False